# Generated by Django 5.2.8 on 2025-11-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات کوتاه')),
                ('base_url', models.URLField(verbose_name='آدرس پایه API')),
                ('documentation_url', models.URLField(blank=True, verbose_name='آدرس مستندات')),
                ('logo', models.URLField(blank=True, verbose_name='لوگو')),
                ('banner', models.URLField(blank=True, verbose_name='بنر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('beta', 'بتا'), ('deprecated', 'منسوخ شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز')),
                ('rating_count', models.IntegerField(default=0, verbose_name='تعداد امتیاز')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='تگ\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_apis', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='api.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True)),
                ('content', models.TextField(verbose_name='محتوای')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='api.api', verbose_name='API')),
            ],
            options={
                'verbose_name': 'مستندات',
                'verbose_name_plural': 'مستندات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('plan_type', models.CharField(choices=[('free', 'رایگان'), ('basic', 'پایه'), ('pro', 'حرفه\u200cای'), ('enterprise', 'سازمانی')], default='basic', max_length=20, verbose_name='نوع پلن')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('requests_per_month', models.IntegerField(blank=True, null=True, verbose_name='درخواست در ماه')),
                ('requests_per_day', models.IntegerField(blank=True, null=True, verbose_name='درخواست در روز')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='api.api', verbose_name='API')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('avatar', models.URLField(blank=True, verbose_name='آواتار')),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='کلید API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_count', models.IntegerField(default=0, verbose_name='تعداد درخواست')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='api.api', verbose_name='API')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از API',
                'verbose_name_plural': 'استفاده از API ها',
                'unique_together': {('user', 'api')},
            },
        ),
    ]
