# Generated by Django 5.2.8 on 2026-04-19 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_userprofile_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز API",
                "verbose_name_plural": "امتیازهای API",
            },
        ),
        migrations.AlterModelOptions(
            name="api",
            options={
                "ordering": ["-is_featured", "-is_popular", "name"],
                "verbose_name": "API",
                "verbose_name_plural": "API ها",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingplan",
            options={
                "ordering": ["price", "name"],
                "verbose_name": "پلن قیمت\u200cگذاری",
                "verbose_name_plural": "پلن\u200cهای قیمت\u200cگذاری",
            },
        ),
        migrations.AlterUniqueTogether(
            name="apiusage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="api",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apis",
                to="api.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_apis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد کننده",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="ویژه"
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="is_popular",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="محبوب"
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="امتیاز",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد امتیاز"),
        ),
        migrations.AlterField(
            model_name="api",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=160, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("inactive", "غیرفعال"),
                    ("beta", "بتا"),
                    ("deprecated", "منسوخ شده"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
        migrations.AlterField(
            model_name="apiusage",
            name="requests_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد درخواست"),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#2563eb",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رنگ باید به فرمت HEX مانند #2563eb باشد.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="رنگ",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="content",
            field=models.TextField(verbose_name="محتوا"),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=160, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="قیمت",
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="requests_per_day",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="درخواست در روز"
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="requests_per_month",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="درخواست در ماه"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=models.CharField(
                blank=True,
                max_length=48,
                null=True,
                unique=True,
                verbose_name="کلید API",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="آواتار"),
        ),
        migrations.AddIndex(
            model_name="api",
            index=models.Index(fields=["slug"], name="api_api_slug_daf95c_idx"),
        ),
        migrations.AddIndex(
            model_name="api",
            index=models.Index(
                fields=["status", "is_featured", "is_popular"],
                name="api_api_status_a6d337_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="api",
            index=models.Index(
                fields=["category", "status"], name="api_api_categor_b71787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="api_categor_slug_794f78_idx"),
        ),
        migrations.AddIndex(
            model_name="documentation",
            index=models.Index(
                fields=["api", "is_active"], name="api_documen_api_id_f21eed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingplan",
            index=models.Index(
                fields=["api", "is_active"], name="api_pricing_api_id_e4a1f9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiusage",
            constraint=models.UniqueConstraint(
                fields=("user", "api"), name="unique_user_api_usage"
            ),
        ),
        migrations.AddField(
            model_name="apirating",
            name="api",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="api.api",
                verbose_name="API",
            ),
        ),
        migrations.AddField(
            model_name="apirating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddConstraint(
            model_name="apirating",
            constraint=models.UniqueConstraint(
                fields=("user", "api"), name="unique_user_api_rating"
            ),
        ),
    ]
