# Generated by Django 5.2.8 on 2026-04-20 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_apirating_alter_api_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rapidapi", "RapidAPI"),
                            ("manual", "Manual"),
                            ("legacy", "Legacy"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="شناسه اشتراک خارجی"
                    ),
                ),
                (
                    "external_customer_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="شناسه مشتری خارجی"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "requests_per_day",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سقف روزانه"
                    ),
                ),
                (
                    "requests_per_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سقف ماهانه"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
            ],
            options={
                "verbose_name": "دسترسی API",
                "verbose_name_plural": "دسترسی\u200cهای API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="api",
            name="canonical_version",
            field=models.CharField(
                default="v1", max_length=20, verbose_name="نسخه مرجع"
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="public_auth_scheme",
            field=models.CharField(
                choices=[
                    ("rapidapi_proxy", "RapidAPI Proxy"),
                    ("api_key", "API Key"),
                    ("none", "None"),
                ],
                default="rapidapi_proxy",
                max_length=32,
                verbose_name="روش احراز هویت عمومی",
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("published", "Published"),
                    ("deprecated", "Deprecated"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="وضعیت انتشار",
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="rapidapi_listing_url",
            field=models.URLField(blank=True, verbose_name="آدرس لیست RapidAPI"),
        ),
        migrations.AddField(
            model_name="api",
            name="rapidapi_package_slug",
            field=models.SlugField(
                blank=True, max_length=120, verbose_name="شناسه بسته RapidAPI"
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="support_url",
            field=models.URLField(blank=True, verbose_name="آدرس پشتیبانی"),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="external_event_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="شناسه رویداد خارجی"
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="source",
            field=models.CharField(
                choices=[
                    ("imported", "Imported"),
                    ("rapidapi_sync", "RapidAPI Sync"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="window_ended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="پایان بازه"
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="window_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="شروع بازه"),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="is_listed_on_rapidapi",
            field=models.BooleanField(default=False, verbose_name="منتشر در RapidAPI"),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="rapidapi_plan_slug",
            field=models.SlugField(
                blank=True, max_length=120, verbose_name="شناسه پلن RapidAPI"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#2563eb",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be in HEX format like #2563eb.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="رنگ",
            ),
        ),
        migrations.AddIndex(
            model_name="api",
            index=models.Index(
                fields=["publication_status", "canonical_version"],
                name="api_api_publica_1086ef_idx",
            ),
        ),
        migrations.AddField(
            model_name="accessgrant",
            name="api",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to="api.api",
                verbose_name="API",
            ),
        ),
        migrations.AddField(
            model_name="accessgrant",
            name="pricing_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_grants",
                to="api.pricingplan",
                verbose_name="پلن",
            ),
        ),
        migrations.AddField(
            model_name="accessgrant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_grants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="access_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_records",
                to="api.accessgrant",
                verbose_name="دسترسی",
            ),
        ),
        migrations.AddIndex(
            model_name="accessgrant",
            index=models.Index(
                fields=["user", "status"], name="api_accessg_user_id_8c1d47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessgrant",
            index=models.Index(
                fields=["api", "status"], name="api_accessg_api_id_3caf25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessgrant",
            index=models.Index(
                fields=["source", "status"], name="api_accessg_source_f19375_idx"
            ),
        ),
    ]
