from django.urls import include, path

from .views import (
    APIDetailView,
    APIDocumentationListView,
    APIEndpointListView,
    APIListView,
    APIPlanListView,
    APIRatingView,
    APISimilarView,
    AccessGrantListView,
    CategoryApisView,
    CategoryDetailView,
    CategoryListView,
    CurrentUserView,
    DocumentationListView,
    GenerateApiKeyView,
    HealthCheckView,
    LoginView,
    LogoutView,
    OpenAPISchemaView,
    PricingPlanListView,
    ProfileView,
    RegisterView,
    SessionLoginView,
    SessionLogoutView,
    SessionRegisterView,
    SessionView,
    SocialAuthProviderListView,
    SocialAuthStartView,
    SubscriptionCheckoutView,
    CurrentSubscriptionView,
    SubscriptionCheckoutConfirmView,
    SubscriptionPlanListView,
    UsageListView,
    UsageStatsView,
)


v1_urlpatterns = [
    path("system/health/", HealthCheckView.as_view(), name="v1-health"),
    path("schema/openapi.json", OpenAPISchemaView.as_view(), name="v1-openapi-schema"),
    path("auth/session/", SessionView.as_view(), name="v1-session"),
    path("auth/register/", SessionRegisterView.as_view(), name="v1-register"),
    path("auth/login/", SessionLoginView.as_view(), name="v1-login"),
    path("auth/social/providers/", SocialAuthProviderListView.as_view(), name="v1-social-auth-providers"),
    path("auth/social/<slug:provider>/start/", SocialAuthStartView.as_view(), name="v1-social-auth-start"),
    path("auth/logout/", SessionLogoutView.as_view(), name="v1-logout"),
    path("account/user/", CurrentUserView.as_view(), name="v1-account-user"),
    path("account/profile/", ProfileView.as_view(), name="v1-profile"),
    path("account/access/", AccessGrantListView.as_view(), name="v1-access"),
    path("account/subscription/", CurrentSubscriptionView.as_view(), name="v1-account-subscription"),
    path("account/subscription/checkout/<int:checkout_id>/", SubscriptionCheckoutView.as_view(), name="v1-account-subscription-checkout"),
    path("account/subscription/checkout/<int:checkout_id>/confirm/", SubscriptionCheckoutConfirmView.as_view(), name="v1-account-subscription-checkout-confirm"),
    path("account/legacy-api-key/", GenerateApiKeyView.as_view(), name="v1-legacy-api-key"),
    path("account/usage/", UsageListView.as_view(), name="v1-usage-list"),
    path("account/usage/stats/", UsageStatsView.as_view(), name="v1-usage-stats"),
    path("catalog/categories/", CategoryListView.as_view(), name="v1-category-list"),
    path("catalog/categories/<slug:slug>/", CategoryDetailView.as_view(), name="v1-category-detail"),
    path("catalog/categories/<slug:slug>/apis/", CategoryApisView.as_view(), name="v1-category-apis"),
    path("catalog/apis/", APIListView.as_view(), name="v1-api-list"),
    path("catalog/apis/<slug:slug>/", APIDetailView.as_view(), name="v1-api-detail"),
    path("catalog/apis/<slug:slug>/similar/", APISimilarView.as_view(), name="v1-api-similar"),
    path("catalog/apis/<slug:slug>/ratings/", APIRatingView.as_view(), name="v1-api-ratings"),
    path("catalog/apis/<slug:slug>/plans/", APIPlanListView.as_view(), name="v1-api-plans"),
    path("catalog/apis/<slug:slug>/docs/", APIDocumentationListView.as_view(), name="v1-api-docs"),
    path("catalog/apis/<slug:slug>/endpoints/", APIEndpointListView.as_view(), name="v1-api-endpoints"),
    path("catalog/pricing-plans/", PricingPlanListView.as_view(), name="v1-pricing-plan-list"),
    path("catalog/subscription-plans/", SubscriptionPlanListView.as_view(), name="v1-subscription-plan-list"),
    path("catalog/documentations/", DocumentationListView.as_view(), name="v1-documentation-list"),
]


urlpatterns = [
    path("v1/", include(v1_urlpatterns)),
    path("health/", HealthCheckView.as_view(), name="health"),
    path("auth/session/", SessionView.as_view(), name="session"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/social/providers/", SocialAuthProviderListView.as_view(), name="social-auth-providers"),
    path("auth/social/<slug:provider>/start/", SocialAuthStartView.as_view(), name="social-auth-start"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("auth/me/", CurrentUserView.as_view(), name="current-user"),
    path("profile/me/", ProfileView.as_view(), name="profile"),
    path("profile/me/generate-api-key/", GenerateApiKeyView.as_view(), name="generate-api-key"),
    path("usage/", UsageListView.as_view(), name="usage-list"),
    path("usage/stats/", UsageStatsView.as_view(), name="usage-stats"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<slug:slug>/", CategoryDetailView.as_view(), name="category-detail"),
    path("categories/<slug:slug>/apis/", CategoryApisView.as_view(), name="category-apis"),
    path("apis/", APIListView.as_view(), name="api-list"),
    path("apis/<slug:slug>/", APIDetailView.as_view(), name="api-detail"),
    path("apis/<slug:slug>/similar/", APISimilarView.as_view(), name="api-similar"),
    path("apis/<slug:slug>/rate/", APIRatingView.as_view(), name="api-rate"),
    path("pricing-plans/", PricingPlanListView.as_view(), name="pricing-plan-list"),
    path("documentations/", DocumentationListView.as_view(), name="documentation-list"),
]
